server:
  servlet:
    context-path: /spacelab/cabinet

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/spacelab2?createDatabaseIfNotExist=true
    username: root
    password: root

springdoc:
  packages-to-scan: com.example.spacelab.controller, com.example.spacelab.model
  packages-to-exclude: com.example.spacelab.repository
  paths-to-match: /api/**
  override-with-generic-response: false
  api-docs:
    enabled: true
    path: /api/docs
  swagger-ui:
    disable-default-swagger-url: true
    path: /api/swagger-ui
    tryItOutEnabled: true
    operationsSorter: alpha
    tagsSorter: alpha
    filter: true

application:
  teamwork:
    apiVersion: v3
    baseUrl: https://denisscompany18.teamwork.com
    projectId: 641861
    token: twp_QrGASGXS0eiIr83897z18EQXoWzV
  aws:
    bucket:
      name: spacelab-dp-bucket
    accessKey: AKIAZ6H5HK6QAOMKNFFW
    secretKey: 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